# rabbitmq-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  type: NodePort
  selector:
    name: rabbitmq-pod
  ports:
  - protocol: TCP
    port: 15672
    nodePort: 30672
    targetPort: 15672
    name: http
  - protocol: TCP
    port: 5672
    targetPort: 5672
    name: amqp
